---
abstract: 'A Crypt::CBC wrapper with key rotation support'
author:
  - 'Binary.com <perl@binary.com>'
build_requires:
  Test::Differences: '0'
  Test::Most: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7, CPAN::Meta::Converter version 2.142690'
license: bsd
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Crypt-NamedKeys
no_index:
  directory:
    - t
    - inc
requires:
  Carp: '0'
  Crypt::CBC: '0'
  Crypt::Rijndael: '0'
  Digest::SHA: '0'
  JSON: '0'
  MIME::Base64: '0'
  Moo: '0'
  String::Compare::ConstantTime: '0'
  Try::Tiny: '0'
  YAML::XS: '0'
  perl: '5.006'
resources:
  repository: https://github.com/binary-com/perl-Crypt-NamedKeys.git
version: v1.0.0
